SELECT U.TITLE, U.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS, 
DATE_FORMAT(R.CREATED_DATE, "%Y-%m-%d") CREATED_DATE
FROM USED_GOODS_BOARD U JOIN USED_GOODS_REPLY R ON U.BOARD_ID = R.BOARD_ID
WHERE U.CREATED_DATE LIKE "2022-10%"
ORDER BY CREATED_DATE ASC, U.TITLE ASC;